version: "3"

services:
    spoofy:
        container_name: spoofy
        build: .
        image: spoofy
        restart: unless-stopped
        ports:
            - "8080:8080"
        command: --debug
